[package]
name = "regresshion-check"
version = "0.3.1"
edition = "2021"

[dependencies]
cidr = "0.2.3"
dns-lookup = "2.0.4"
libc = "0.2.155"
regex = "1.10.5"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.120"
tokio = { version = "1.38.0", features = ["full"] }
